### ISSUE TITLE
gracefully handel paths.yml

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_env_manager#12]
**what happens**:
1. run 'wc_env_manager container build' with a wc_env_manager.cfg in ~/.wc
2. get:
Traceback (most recent call last):
  File "/anaconda3/bin/wc_env_manager", line 11, in <module>
    sys.exit(main())
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_dev_repos/wc_env_manager/wc_env_manager/__main__.py", line 268, in main
    app.run()
  File "/anaconda3/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/anaconda3/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 806, in _dispatch
    return func()
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_dev_repos/wc_env_manager/wc_env_manager/__main__.py", line 170, in build
    mgr.setup_container()
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_dev_repos/wc_env_manager/wc_env_manager/core.py", line 643, in setup_container
    self.get_config_file_paths_to_copy_to_image() \
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_dev_repos/wc_env_manager/wc_env_manager/core.py", line 439, in get_config_file_paths_to_copy_to_image
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/arthur_at_sinai/.wc/third_party/paths.yml'

 **what's expected**:
1. error message which should a) explain why the file ~/.wc/third_party/paths.yml is expected, b) point to documentation on how to avoid the error

**Comment by jonrkarr** [comment]
Added warning which explains this and provides link to an example
